spring:
  application:
    name : infirmary-application
    base-url : "http://localhost:8080"
    endpoints:
      reset-password: "/user/reset-password?token="
      parent-endpoint: "/parent/view/student-profile?token="
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: infirmary
    password: Changeme0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.springframework.security.web: info
      root: info
    file:
      name: build/log/${spring.application.name}.log
jwt:
  secret: 'thebigbrownfoxjumpsoverthelazydog'

